# Generated by Django 4.1 on 2022-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=4000)),
                ('preparation_time', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
