# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DividendsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DivWindow(object):
    def setupUi(self, DivWindow):
        DivWindow.setObjectName("DivWindow")
        DivWindow.resize(1088, 612)
        DivWindow.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(DivWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DivView = QtWidgets.QTableView(self.centralwidget)
        self.DivView.setGeometry(QtCore.QRect(40, 90, 321, 431))
        self.DivView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DivView.setObjectName("DivView")
        self.DivTicker = QtWidgets.QLineEdit(self.centralwidget)
        self.DivTicker.setGeometry(QtCore.QRect(120, 30, 171, 31))
        self.DivTicker.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DivTicker.setObjectName("DivTicker")
        self.DivDate = QtWidgets.QDateEdit(self.centralwidget)
        self.DivDate.setGeometry(QtCore.QRect(420, 30, 161, 31))
        self.DivDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DivDate.setObjectName("DivDate")
        self.ShowDiv = QtWidgets.QPushButton(self.centralwidget)
        self.ShowDiv.setGeometry(QtCore.QRect(620, 20, 131, 51))
        self.ShowDiv.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.ShowDiv.setObjectName("ShowDiv")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 35, 91, 21))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.DivPlot = MplWidget(self.centralwidget)
        self.DivPlot.setGeometry(QtCore.QRect(389, 99, 671, 411))
        self.DivPlot.setObjectName("DivPlot")
        DivWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DivWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 26))
        self.menubar.setObjectName("menubar")
        DivWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DivWindow)
        self.statusbar.setObjectName("statusbar")
        DivWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DivWindow)
        QtCore.QMetaObject.connectSlotsByName(DivWindow)

    def retranslateUi(self, DivWindow):
        _translate = QtCore.QCoreApplication.translate
        DivWindow.setWindowTitle(_translate("DivWindow", "MainWindow"))
        self.ShowDiv.setText(_translate("DivWindow", "Show"))
        self.label.setText(_translate("DivWindow", "Ticker:"))
        self.label_2.setText(_translate("DivWindow", "Onward: "))
from mplwidget import MplWidget
