# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PricesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 737)
        Form.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.PriceTicker = QtWidgets.QLineEdit(Form)
        self.PriceTicker.setGeometry(QtCore.QRect(90, 30, 151, 31))
        self.PriceTicker.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PriceTicker.setObjectName("PriceTicker")
        self.PriceShow = QtWidgets.QPushButton(Form)
        self.PriceShow.setGeometry(QtCore.QRect(770, 50, 121, 41))
        self.PriceShow.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.PriceShow.setObjectName("PriceShow")
        self.DailyInt = QtWidgets.QRadioButton(Form)
        self.DailyInt.setGeometry(QtCore.QRect(650, 40, 95, 20))
        self.DailyInt.setObjectName("DailyInt")
        self.WeeklyInt = QtWidgets.QRadioButton(Form)
        self.WeeklyInt.setGeometry(QtCore.QRect(650, 70, 95, 20))
        self.WeeklyInt.setObjectName("WeeklyInt")
        self.MonthlyInt = QtWidgets.QRadioButton(Form)
        self.MonthlyInt.setGeometry(QtCore.QRect(650, 100, 95, 20))
        self.MonthlyInt.setObjectName("MonthlyInt")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(650, 10, 111, 16))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 111, 16))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(360, 90, 111, 16))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.StartDate = QtWidgets.QDateEdit(Form)
        self.StartDate.setGeometry(QtCore.QRect(159, 81, 121, 31))
        self.StartDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.StartDate.setObjectName("StartDate")
        self.EndDate = QtWidgets.QDateEdit(Form)
        self.EndDate.setGeometry(QtCore.QRect(470, 80, 121, 31))
        self.EndDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EndDate.setObjectName("EndDate")
        self.PricePlot = MplWidget(Form)
        self.PricePlot.setGeometry(QtCore.QRect(40, 130, 851, 511))
        self.PricePlot.setObjectName("PricePlot")
        self.PredictButton = QtWidgets.QPushButton(Form)
        self.PredictButton.setGeometry(QtCore.QRect(50, 660, 201, 41))
        self.PredictButton.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.PredictButton.setObjectName("PredictButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(280, 660, 171, 31))
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.FuturePeriods = QtWidgets.QLineEdit(Form)
        self.FuturePeriods.setGeometry(QtCore.QRect(460, 660, 41, 41))
        self.FuturePeriods.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FuturePeriods.setObjectName("FuturePeriods")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(510, 660, 131, 31))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.FuturePrice = QtWidgets.QTextBrowser(Form)
        self.FuturePrice.setGeometry(QtCore.QRect(640, 660, 131, 41))
        self.FuturePrice.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.FuturePrice.setObjectName("FuturePrice")
        self.PredictButton_2 = QtWidgets.QPushButton(Form)
        self.PredictButton_2.setGeometry(QtCore.QRect(790, 660, 201, 41))
        self.PredictButton_2.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.PredictButton_2.setObjectName("PredictButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PriceShow.setText(_translate("Form", "Show"))
        self.DailyInt.setText(_translate("Form", "Daily"))
        self.WeeklyInt.setText(_translate("Form", "Weekly"))
        self.MonthlyInt.setText(_translate("Form", "Monthly"))
        self.label.setText(_translate("Form", "Interval:"))
        self.label_2.setText(_translate("Form", "Ticker:"))
        self.label_3.setText(_translate("Form", "Start date:"))
        self.label_4.setText(_translate("Form", "End date:"))
        self.PredictButton.setText(_translate("Form", "Predict"))
        self.label_5.setText(_translate("Form", "Stock price in next"))
        self.label_6.setText(_translate("Form", "intervals is :"))
        self.PredictButton_2.setText(_translate("Form", "Submit"))
from mplwidget import MplWidget
